/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.TalentoHumano;

import controlador.ControladorTalentoHumano;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JButton;

/**
 *
 * @author CARLOS
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Point posicion1;
    private final Point posicion2;
    private final Dimension tamaño;
    private boolean bandera;
    
    public VentanaPrincipal() {
        initComponents();
        posicion1 = botonTrabajador.getLocation();
        posicion2 = botonReporte.getLocation();
        tamaño = botonTrabajador.getSize();
        bandera = true;
    }

    public Point getPosicion1() {
        return posicion1;
    }

    public Point getPosicion2() {
        return posicion2;
    }

    public Dimension getTamaño() {
        return tamaño;
    }

    public boolean isBandera() {
        return bandera;
    }

    public JButton getBotonActualizar() {
        return botonActualizar;
    }

    public JButton getBotonAñadir() {
        return botonAñadir;
    }

    public JButton getBotonEliminar() {
        return botonEliminar;
    }

    public JButton getBotonGenerarReporte() {
        return botonGenerarReporte;
    }

    public JButton getBotonReporte() {
        return botonReporte;
    }

    public JButton getBotonTrabajador() {
        return botonTrabajador;
    }

    public void setControlador(ControladorTalentoHumano c){
        botonTrabajador.addActionListener(c);
        botonAñadir.addActionListener(c);
        botonActualizar.addActionListener(c);
        botonEliminar.addActionListener(c);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAñadir = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGenerarReporte = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        ListadoDeTrabajadores listado = new ListadoDeTrabajadores(); 
        escritorio.add(listado);
        listado.show();
        botonTrabajador = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();

        botonAñadir.setText("Añadir");

        botonActualizar.setText("Actualizar");

        botonEliminar.setText("Eliminar");

        botonGenerarReporte.setText("Generar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        botonTrabajador.setText("Trabajadores");

        botonReporte.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(botonTrabajador)
                .addGap(35, 35, 35)
                .addComponent(botonReporte))
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonTrabajador;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
