/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.TalentoHumano;

import com.placeholder.PlaceHolder;
import controlador.ControladorTalentoHumano;
import java.awt.Dimension;
import java.awt.Point;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author CARLOS
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Point posicion1;
    private final Point posicion2;
    private final Dimension tamaño;
    private boolean bandera;
    
    public VentanaPrincipal() {
        initComponents();
        posicion1 = botonTrabajador.getLocation();
        posicion2 = botonReporte.getLocation();
        tamaño = botonTrabajador.getSize();
        bandera = true;
    }

    public Point getPosicion1() {
        return posicion1;
    }

    public Point getPosicion2() {
        return posicion2;
    }

    public Dimension getTamaño() {
        return tamaño;
    }

    public boolean isBandera() {
        return bandera;
    }

    public JButton getBotonActualizar() {
        return botonActualizar;
    }

    public JButton getBotonAñadir() {
        return botonAñadir;
    }

    public JButton getBotonEliminar() {
        return botonEliminar;
    }

    public JButton getBotonGenerarReporte() {
        return botonGenerarReporte;
    }

    public JButton getBotonReporte() {
        return botonReporte;
    }

    public JButton getBotonTrabajador() {
        return botonTrabajador;
    }

    public JTextField getBusquedaCargo() {
        return busquedaCargo;
    }

    public JTextField getBusquedaDNI() {
        return busquedaDNI;
    }

    public JTextField getBusquedaNombre() {
        return busquedaNombre;
    }

    public JTable getTablaTrabajadores() {
        return tablaTrabajadores;
    }

    public void setControlador(ControladorTalentoHumano c){
        botonTrabajador.addActionListener(c);
        botonAñadir.addActionListener(c);
        botonActualizar.addActionListener(c);
        botonEliminar.addActionListener(c);
        busquedaDNI.addKeyListener(c);
        busquedaCargo.addKeyListener(c);
        busquedaNombre.addKeyListener(c);
        tablaTrabajadores.addMouseListener(c);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAñadir = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGenerarReporte = new javax.swing.JButton();
        botonTrabajador = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();
        panelListados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        busquedaDNI = new javax.swing.JTextField();
        PlaceHolder texto = new PlaceHolder(busquedaDNI, "DNI");
        busquedaNombre = new javax.swing.JTextField();
        PlaceHolder texto2 = new PlaceHolder(busquedaNombre, "Nombre");
        busquedaCargo = new javax.swing.JTextField();
        PlaceHolder texto3 = new PlaceHolder(busquedaCargo, "Cargo");

        botonAñadir.setText("Añadir");

        botonActualizar.setText("Actualizar");

        botonEliminar.setText("Eliminar");

        botonGenerarReporte.setText("Generar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonTrabajador.setText("Trabajadores");

        botonReporte.setText("Reportes");

        panelListados.setMinimumSize(new java.awt.Dimension(451, 361));
        panelListados.setPreferredSize(new java.awt.Dimension(451, 361));
        panelListados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Cargo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTrabajadores);

        panelListados.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 388, 231));
        panelListados.add(busquedaDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 110, -1));
        panelListados.add(busquedaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 110, -1));
        panelListados.add(busquedaCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(panelListados, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(botonTrabajador)
                .addGap(35, 35, 35)
                .addComponent(botonReporte)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(panelListados, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonTrabajador;
    private javax.swing.JTextField busquedaCargo;
    private javax.swing.JTextField busquedaDNI;
    private javax.swing.JTextField busquedaNombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelListados;
    private javax.swing.JTable tablaTrabajadores;
    // End of variables declaration//GEN-END:variables
}
