/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.SistemaVentas;


import com.placeholder.PlaceHolder;

/**
 *
 * @author CARLOS
 */
public class ListadoDePedidos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListadoDeTrabajadores
     */
    public ListadoDePedidos() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        busquedaCodigo = new javax.swing.JTextField();
        PlaceHolder texto = new PlaceHolder(busquedaCodigo, "Código");
        busquedaCliente = new javax.swing.JTextField();
        PlaceHolder texto2 = new PlaceHolder(busquedaCliente, "Cliente");
        busquedaFecha = new javax.swing.JTextField();
        PlaceHolder texto3 = new PlaceHolder(busquedaFecha, "Fecha");
        busquedaImporte = new javax.swing.JTextField();
        PlaceHolder texto4 = new PlaceHolder(busquedaImporte, "Importe");
        busquedaEstado = new javax.swing.JTextField();
        PlaceHolder texto5 = new PlaceHolder(busquedaEstado, "Estado");

        setMinimumSize(new java.awt.Dimension(623, 480));
        setPreferredSize(new java.awt.Dimension(623, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Cliente", "Fecha", "Importe Total", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaTrabajadores);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 111, 520, 260));
        getContentPane().add(busquedaCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 90, 25));
        getContentPane().add(busquedaCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 90, 25));
        getContentPane().add(busquedaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 90, 25));
        getContentPane().add(busquedaImporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 90, 25));
        getContentPane().add(busquedaEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 70, 90, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField busquedaCliente;
    private javax.swing.JTextField busquedaCodigo;
    private javax.swing.JTextField busquedaEstado;
    private javax.swing.JTextField busquedaFecha;
    private javax.swing.JTextField busquedaImporte;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaTrabajadores;
    // End of variables declaration//GEN-END:variables
}
