/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.Logistica;

import vista.propiedad.Directorio;
import vista.SistemaVentas.ListadoDeClientes;
import vista.SistemaVentas.ListadoDePedidos;
import vista.SistemaVentas.ListadoDeTarifas;
import vista.SistemaVentas.FormularioCliente;
import vista.SistemaVentas.FormularioTarifa;
import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author CARLOS
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Point posicion1;
    private final Point posicion2;
    private final Dimension tamaño;
    private boolean bandera;
    private boolean bandera2;
    private boolean bandera3;
    private final ListadoDeClientes listado1;
    private final ListadoDePedidos listado2;
    private final ListadoDeTarifas listado3;
    
    
    public VentanaPrincipal() {
        initComponents();
        
        posicion1 = botonEntrega.getLocation();
        posicion2 = botonProduccion.getLocation();
        tamaño = botonEntrega.getSize();
        
        bandera = true;
        bandera2 = true;
        bandera3 = true;
        
        listado1 = new ListadoDeClientes();
        listado2 = new ListadoDePedidos();
        listado3 = new ListadoDeTarifas();
        
        ponerImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAñadirCliente = new javax.swing.JButton();
        botonActualizarCliente = new javax.swing.JButton();
        botonEliminarCliente = new javax.swing.JButton();
        botonAñadirPedido = new javax.swing.JButton();
        botonActualizarPedido = new javax.swing.JButton();
        botonEliminarPedido = new javax.swing.JButton();
        botonAñadirTarifa = new javax.swing.JButton();
        botonActualizarTarifa = new javax.swing.JButton();
        botonEliminarTarifa = new javax.swing.JButton();
        contenedorBotones = new javax.swing.JPanel();
        botonEntrega = new javax.swing.JButton();
        botonProduccion = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();

        botonAñadirCliente.setBackground(new java.awt.Color(255, 169, 26));
        botonAñadirCliente.setText("Añadir");
        botonAñadirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirClienteActionPerformed(evt);
            }
        });

        botonActualizarCliente.setBackground(new java.awt.Color(255, 169, 26));
        botonActualizarCliente.setText("Actualizar");

        botonEliminarCliente.setBackground(new java.awt.Color(255, 169, 26));
        botonEliminarCliente.setText("Eliminar");

        botonAñadirPedido.setBackground(new java.awt.Color(255, 169, 26));
        botonAñadirPedido.setText("Añadir");

        botonActualizarPedido.setBackground(new java.awt.Color(255, 169, 26));
        botonActualizarPedido.setText("Actualizar");

        botonEliminarPedido.setBackground(new java.awt.Color(255, 169, 26));
        botonEliminarPedido.setText("Eliminar");

        botonAñadirTarifa.setBackground(new java.awt.Color(255, 169, 26));
        botonAñadirTarifa.setText("Añadir");
        botonAñadirTarifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAñadirTarifaActionPerformed(evt);
            }
        });

        botonActualizarTarifa.setBackground(new java.awt.Color(255, 169, 26));
        botonActualizarTarifa.setText("Actualizar");

        botonEliminarTarifa.setBackground(new java.awt.Color(255, 169, 26));
        botonEliminarTarifa.setText("Eliminar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contenedorBotones.setBackground(new java.awt.Color(0, 204, 204));
        contenedorBotones.setForeground(new java.awt.Color(255, 153, 0));

        botonEntrega.setBackground(new java.awt.Color(255, 169, 26));
        botonEntrega.setForeground(new java.awt.Color(0, 0, 0));
        botonEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/iconos/entrega.png"))); // NOI18N
        botonEntrega.setText("Entrega");
        botonEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEntregaActionPerformed(evt);
            }
        });

        botonProduccion.setBackground(new java.awt.Color(255, 169, 26));
        botonProduccion.setForeground(new java.awt.Color(0, 0, 0));
        botonProduccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/frame/imagenes/iconos/produccion.png"))); // NOI18N
        botonProduccion.setText("Producción");
        botonProduccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProduccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenedorBotonesLayout = new javax.swing.GroupLayout(contenedorBotones);
        contenedorBotones.setLayout(contenedorBotonesLayout);
        contenedorBotonesLayout.setHorizontalGroup(
            contenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBotonesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorBotonesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonProduccion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78))
        );
        contenedorBotonesLayout.setVerticalGroup(
            contenedorBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorBotonesLayout.createSequentialGroup()
                .addContainerGap(188, Short.MAX_VALUE)
                .addComponent(botonEntrega)
                .addGap(26, 26, 26)
                .addComponent(botonProduccion)
                .addGap(126, 126, 126)
                .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        botonSalir.setOpaque(false);
        botonSalir.setContentAreaFilled(false);
        botonSalir.setBorderPainted(false);

        getContentPane().add(contenedorBotones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 285, 470));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 623, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 476, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 0, -1, 476));
        ListadoDeClientes lista = new ListadoDeClientes();
        lista.setPreferredSize(escritorio.getPreferredSize());
        escritorio.add(lista);
        lista.show();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEntregaActionPerformed
        int posicionX = posicion1.x;
        int posicionY = posicion1.y;
        
        if(bandera){
        
            botonAñadirCliente.setBounds(posicionX + 10, posicionY + 47, tamaño.width - 20, tamaño.height-13);
            contenedorBotones.add(botonAñadirCliente);

            botonActualizarCliente.setBounds(posicionX + 10, posicionY + 77, tamaño.width - 20, tamaño.height-13);
            contenedorBotones.add(botonActualizarCliente);

            botonEliminarCliente.setBounds(posicionX + 10, posicionY + 107, tamaño.width - 20, tamaño.height-13);
            contenedorBotones.add(botonEliminarCliente);

            botonProduccion.setBounds(posicionX, posicionY + 145, tamaño.width, tamaño.height);
            contenedorBotones.add(botonProduccion);
            
            
            bandera = false;
        } 
        else{
            contenedorBotones.remove(botonAñadirCliente);
            contenedorBotones.remove(botonActualizarCliente);
            contenedorBotones.remove(botonEliminarCliente);

            botonProduccion.setBounds(posicion2.x, posicion2.y, tamaño.width, tamaño.height);
            contenedorBotones.add(botonProduccion);                
            
            bandera = true;
        }
    }//GEN-LAST:event_botonEntregaActionPerformed

    private void botonProduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProduccionActionPerformed
        int posicionX = posicion2.x;
        int posicionY = posicion2.y;
        
        if(bandera2){
            escritorio.add(listado2);
            listado2.show();
            
            botonAñadirPedido.setBounds(posicionX + 10, posicionY + 30, tamaño.width - 20, tamaño.height);
            contenedorBotones.add(botonAñadirPedido);

            botonActualizarPedido.setBounds(posicionX + 10, posicionY + 60, tamaño.width - 20, tamaño.height);
            contenedorBotones.add(botonActualizarPedido);

            botonEliminarPedido.setBounds(posicionX + 10, posicionY + 90, tamaño.width - 20, tamaño.height);
            contenedorBotones.add(botonEliminarPedido);
            
            bandera2 = false;
        } 
        else{
            contenedorBotones.remove(botonAñadirPedido);
            contenedorBotones.remove(botonActualizarPedido);
            contenedorBotones.remove(botonEliminarPedido);
            
            bandera2 = true;
        }
    }//GEN-LAST:event_botonProduccionActionPerformed

    private void botonAñadirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirClienteActionPerformed
        this.setVisible(false);
        
        FormularioCliente cliente = new FormularioCliente();
        cliente.setVisible(true);
        cliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonAñadirClienteActionPerformed

    private void botonAñadirTarifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAñadirTarifaActionPerformed
        this.setVisible(false);
        
        FormularioTarifa tarifa = new FormularioTarifa();
        tarifa.setVisible(true);
        tarifa.setLocationRelativeTo(null);
    }//GEN-LAST:event_botonAñadirTarifaActionPerformed

    private void ponerImagenes(){
        //Directorio.ponerImagenBoton(botonAtras, Directorio.botonAtras);
        Directorio.ponerImagenBoton(botonSalir, Directorio.botonSalir);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizarCliente;
    private javax.swing.JButton botonActualizarPedido;
    private javax.swing.JButton botonActualizarTarifa;
    private javax.swing.JButton botonAñadirCliente;
    private javax.swing.JButton botonAñadirPedido;
    private javax.swing.JButton botonAñadirTarifa;
    private javax.swing.JButton botonEliminarCliente;
    private javax.swing.JButton botonEliminarPedido;
    private javax.swing.JButton botonEliminarTarifa;
    private javax.swing.JButton botonEntrega;
    private javax.swing.JButton botonProduccion;
    private javax.swing.JButton botonSalir;
    private javax.swing.JPanel contenedorBotones;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
