/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame.TalentoHumano;

import java.awt.Dimension;
import java.awt.Point;

/**
 *
 * @author CARLOS
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    private final Point posicion1;
    private final Point posicion2;
    private final Dimension tamaño;
    private boolean bandera;
    
    public VentanaPrincipal() {
        initComponents();
        posicion1 = botonTrabajador.getLocation();
        posicion2 = botonReporte.getLocation();
        tamaño = botonTrabajador.getSize();
        bandera = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonAñadir = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonEliminar = new javax.swing.JButton();
        botonGenerarReporte = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        ListadoDeTrabajadores listado = new ListadoDeTrabajadores(); 
        escritorio.add(listado);
        listado.show();
        botonTrabajador = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();

        botonAñadir.setText("Añadir");

        botonActualizar.setText("Actualizar");

        botonEliminar.setText("Eliminar");

        botonGenerarReporte.setText("Generar");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 471, Short.MAX_VALUE)
        );

        botonTrabajador.setText("Trabajadores");
        botonTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrabajadorActionPerformed(evt);
            }
        });

        botonReporte.setText("Reportes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonTrabajador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(botonTrabajador)
                .addGap(35, 35, 35)
                .addComponent(botonReporte))
            .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrabajadorActionPerformed
        int posicionX = posicion1.x;
        int posicionY = posicion1.y;
        
        if(bandera){
            botonAñadir.setBounds(posicionX + 10, posicionY + 30, tamaño.width - 20, tamaño.height);
            this.add(botonAñadir);

            botonActualizar.setBounds(posicionX + 10, posicionY + 60, tamaño.width - 20, tamaño.height);
            this.add(botonActualizar);

            botonEliminar.setBounds(posicionX + 10, posicionY + 90, tamaño.width - 20, tamaño.height);
            this.add(botonEliminar);

            botonReporte.setBounds(posicionX, posicionY + 140, tamaño.width, tamaño.height);
            this.add(botonReporte);
            
            bandera = false;
        } 
        else{
            this.remove(botonAñadir);
            this.remove(botonActualizar);
            this.remove(botonEliminar);

            botonReporte.setBounds(posicionX, posicion2.y, tamaño.width, tamaño.height);
            this.add(botonReporte);
            
            bandera = true;
        }
        
    }//GEN-LAST:event_botonTrabajadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonAñadir;
    private javax.swing.JButton botonEliminar;
    private javax.swing.JButton botonGenerarReporte;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonTrabajador;
    private javax.swing.JDesktopPane escritorio;
    // End of variables declaration//GEN-END:variables
}
